FROM python:latest

RUN mkdir -p /smetrics
RUN mkdir -p /var/log/collector/xtremio

WORKDIR /smetrics

COPY . params.py
COPY . common_functions.py
COPY . isilon_collector.py

CMD ["/usr/local/bin/python isilon_collector.py"]
