FROM python:latest

COPY requirements.txt requirements.txt
COPY params.py params.py
COPY common_functions.py common_functions.py
COPY xtremio_collector.py xtremio_collector.py

RUN /usr/local/bin/pip install -r requirements.txt