FROM python:latest

RUN mkdir -p /emc
RUN mkdir -p /var/log/collector/xtremio

WORKDIR /emc

COPY . params.py
COPY . common_functions.py
COPY . isilon_collector.py

CMD ["/usr/local/bin/python isilon_collector.py"]
