FROM python:latest

RUN mkdir -p /smetrics
RUN mkdir -p /var/log/controller

WORKDIR /smetrics

COPY . params.py
COPY . common_functions.py
COPY . controller.py

CMD ["/usr/local/bin/python controller.py"]
