FROM python:latest

RUN mkdir -p /smetrics
RUN mkdir -p /var/log/collector/xtremio

WORKDIR /smetrics

COPY ./requirements.txt requirements.txt
COPY ./params.py params.py
COPY ./common_functions.py common_functions.py
COPY ./xtremio_collector.py xtremio_collector.py

RUN pip install -r requirements.txt
