FROM python:latest

RUN mkdir -p /smetrics
RUN mkdir -p /var/log/controller

WORKDIR /smetrics

COPY ./requirements.txt requirements.txt
COPY ./params.py params.py
COPY ./common_functions.py common_functions.py
COPY ./controller.py controller.py

RUN pip install -r requirements.txt
